services:
  jenkins:
    container_name: jenkins
    network_mode: host
    build: config/jenkins
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/jcasc
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
    volumes:
      - ./config/jenkins:/var/jenkins_home/config:ro
      - ./config/jenkins/jenkins.yml:/var/jenkins_home/jcasc/jenkins.yml:ro
  otel-collector:
    container_name: otel-collector
    network_mode: host
    image: otel/opentelemetry-collector:0.24.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
      - ./data/otel-collector:/data/otel-collector
  prometheus:
    container_name: prometheus
    network_mode: host
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
