services:
  jenkins:
    container_name: jenkins
    network_mode: host
    build: config/jenkins
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/jcasc
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
    volumes:
      - ./config/jenkins:/var/jenkins_home/config:ro
      - ./config/jenkins/jenkins.yml:/var/jenkins_home/jcasc/jenkins.yml:ro
  otel-collector:
    container_name: otel-collector
    network_mode: host
    image: otel/opentelemetry-collector:0.24.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
      - ./data/otel-collector:/data/otel-collector
  prometheus:
    container_name: prometheus
    network_mode: host
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    network_mode: host
    image: opensearchproject/data-prepper:latest
    volumes:
      - ./config/data-prepper/pipelines.yaml:/usr/share/data-prepper/pipelines.yaml
      - ./config/data-prepper/data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml
  opensearch:
    container_name: opensearch
    network_mode: host
    image: opensearchproject/opensearch:latest
    environment:
      - "discovery.type=single-node"
      - "DISABLE_SECURITY_PLUGIN=true"
  opensearch-dashboards:
    container_name: opensearch-dashboards
    network_mode: host
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      - "OPENSEARCH_HOSTS=http://localhost:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" 
  jaeger-collector:
    restart: unless-stopped
    container_name: jaeger-collector
    network_mode: host
    image: jaegertracing/jaeger-collector
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://localhost:9200"
  jaeger-query:
    restart: unless-stopped
    container_name: jaeger-query
    network_mode: host
    image: jaegertracing/jaeger-query
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://localhost:9200"
