jobs:
  - file: "/var/jenkins_home/config/example.job"
unclassified:
  openTelemetry:
    authentication: "noAuthentication"
    endpoint: "http://localhost:55680"
    exportOtelConfigurationAsEnvironmentVariables: true
