receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  logging:
  file:
    path: /data/otel-collector/otel.json
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp/2:
    endpoint: localhost:21890
    insecure: true
  jaeger:
    endpoint: localhost:14250
    insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,file,otlp/2,jaeger]
    metrics:
      receivers: [otlp]
      exporters: [logging,file,prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging,file]
