receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

exporters:
  logging:
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp/2:
    endpoint: localhost:21890
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,otlp/2]
    metrics:
      receivers: [otlp]
      exporters: [logging,prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging]
